# Generated by Django 4.1.5 on 2023-01-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='relevance', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
                ('graph_up', models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика количества вакансий по годам')),
                ('graph_middle', models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика уровня зарплат по годам для профессии')),
                ('graph_down', models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика количества вакансий по годам для профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='geography', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
                ('table', models.TextField(default=None, verbose_name='Уровень зарплат по городам')),
                ('graph', models.ImageField(default=None, upload_to='geography', verbose_name='Доля вакансий по городам')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='homepage', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
                ('image', models.ImageField(default=None, upload_to='home', verbose_name='Главное изображение')),
                ('image_second', models.ImageField(default=None, upload_to='home', verbose_name='Второе изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='skills', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
            ],
        ),
    ]
