# Generated by Django 4.1.5 on 2023-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='geography', max_length=100, verbose_name='Заголовок')),
                ('table_salary', models.TextField(default=None, verbose_name='Таблица о зарплате')),
                ('table_percent', models.TextField(default=None, verbose_name='Таблица о проценте')),
                ('graph', models.ImageField(default=None, upload_to='geography', verbose_name='График доли вакансий по городам')),
                ('result', models.TextField(default=None, verbose_name='Результат анализа по странице')),
            ],
            options={
                'verbose_name': 'geography page',
                'verbose_name_plural': 'geography pages',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='homepage', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
                ('image', models.ImageField(default=None, upload_to='home', verbose_name='Главное изображение')),
                ('image_second', models.ImageField(default=None, upload_to='home', verbose_name='Второе изображение')),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home pages',
            },
        ),
        migrations.CreateModel(
            name='LastVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='last_vacancies', max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'vacancy page',
                'verbose_name_plural': 'vacancies pages',
            },
        ),
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='relevance', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
                ('graph_up', models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика уровня зарплат по годам для профессии')),
                ('graph_middle', models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика количества вакансий по годам')),
                ('graph_down', models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика количества вакансий по годам для профессии')),
                ('result', models.TextField(default=None, verbose_name='Результат анализа по странице')),
            ],
            options={
                'verbose_name': 'relevance page',
                'verbose_name_plural': 'relevance pages',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='skills', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Содержимое')),
                ('result', models.TextField(default=None, verbose_name='Результат анализа по странице')),
            ],
            options={
                'verbose_name': 'skills page',
                'verbose_name_plural': 'skills pages',
            },
        ),
    ]
