# Generated by Django 4.1.5 on 2023-01-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demand',
            new_name='Relevance',
        ),
    ]
