# Generated by Django 4.1.5 on 2023-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_demand_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='last_vacancies', max_length=100, verbose_name='Заголовок')),
            ],
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph',
            field=models.ImageField(default=None, upload_to='geography', verbose_name='График доли вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='table',
            field=models.TextField(default=None, verbose_name='Таблица уровня зарплат по городам'),
        ),
        migrations.AlterField(
            model_name='relevance',
            name='graph_middle',
            field=models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика количества вакансий по годам'),
        ),
        migrations.AlterField(
            model_name='relevance',
            name='graph_up',
            field=models.ImageField(default=None, upload_to='relevance', verbose_name='Динамика уровня зарплат по годам для профессии'),
        ),
    ]
